/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registrohospital;

import javax.swing.JOptionPane;

/**
 *
 * @author Legion
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JFrame();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        Ficha = new javax.swing.JFrame();
        rut = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        Nuevo = new javax.swing.JFrame();
        rut_n = new javax.swing.JLabel();
        txtrut_n = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField12 = new javax.swing.JTextField();
        Visualizar = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Eliminar = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Modificar = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        Elegir = new javax.swing.JFrame();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();

        Menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setText("Modificara Datos de Paciente");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 294, -1));

        btnAgregar.setText("Agregar Paciente");
        Menu.getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 294, -1));

        btnVer.setText("Ver Datos de Paciente");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 294, -1));

        Ficha.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rut.setText("Rut:");
        Ficha.getContentPane().add(rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txt_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutActionPerformed(evt);
            }
        });
        Ficha.getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 230, -1));

        jLabel3.setText("Nombre:");
        Ficha.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        Ficha.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, -1));

        jLabel4.setText("Apellido:");
        Ficha.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setText("Edad:");
        Ficha.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setText("Motivo Consulta:");
        Ficha.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel7.setText("Fecha Ingreso:");
        Ficha.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel8.setText("Pasillo:");
        Ficha.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel9.setText("Estado:");
        Ficha.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel10.setText("Comentarios:");
        Ficha.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        Ficha.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 230, -1));
        Ficha.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));
        Ficha.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, -1));
        Ficha.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 230, -1));
        Ficha.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 230, -1));

        jTextField7.setText("Caja grande de texto con scroll");
        Ficha.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dado de alta", "En Riesgo", "Estado critico" }));
        Ficha.getContentPane().add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        Nuevo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rut_n.setText("Rut");
        Nuevo.getContentPane().add(rut_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));
        Nuevo.getContentPane().add(txtrut_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, -1));

        jLabel11.setText("Nombre");
        Nuevo.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        Nuevo.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, -1));

        jLabel12.setText("Apellido");
        Nuevo.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        Nuevo.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, -1));

        jLabel13.setText("Edad");
        Nuevo.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        Nuevo.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 40, -1));

        jLabel14.setText("Fecha Ingreso:");
        Nuevo.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel15.setText("Motivo consulta");
        Nuevo.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        Nuevo.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));

        jLabel16.setText("Pasillo");
        Nuevo.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasillo A", "Pasillo B" }));
        Nuevo.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel17.setText("Estado");
        Nuevo.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dado de alta", "en riesgo", "Estado critico" }));
        Nuevo.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel18.setText("Contraseña");
        Nuevo.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jPasswordField1.setText("jPasswordField1");
        Nuevo.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));
        Nuevo.getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, -1));

        Visualizar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Pasillo:");
        Visualizar.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Visualizar.getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel20.setText("Buscar:");
        Visualizar.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre", "Apellido", "Edad", "Motivo", "Fecha de Ingreso", "Pasillo", "Estado", "Comentarios"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Visualizar.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 820, 240));
        Visualizar.getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jButton4.setText("Buscar");
        Visualizar.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jButton5.setText("Ver ficha");
        Visualizar.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jButton6.setText("Editar");
        Visualizar.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jButton7.setText("Eliminar");
        Visualizar.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jButton8.setText("Actualizar");
        Visualizar.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        Eliminar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Eliminar Paciente");
        Eliminar.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 40));

        jLabel22.setText("RUT del paciente:");
        Eliminar.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        Eliminar.getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, -1));

        jButton1.setText("Buscar");
        Eliminar.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del paciente"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Nombre:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, -1));

        jLabel24.setText("Apellido:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        jButton2.setText("Eliminar Paciente");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jButton3.setText("Cancelar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        Eliminar.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 580, 190));

        Modificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Modificar Paciente");
        Modificar.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel26.setText("RUT del Paciente:");
        Modificar.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        Modificar.getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, -1));

        jButton9.setText("Buscar");
        Modificar.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Nombre:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));

        jLabel28.setText("Apellido:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, -1));

        jButton10.setText("Guardar Cambios");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jButton11.setText("Cancelar");
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel29.setText("Edad:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 200, -1));

        jLabel30.setText("Motivo Consulta:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel31.setText("Fecha de Ingreso:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        jLabel32.setText("Pasillo:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, -1));

        jLabel33.setText("Estado:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dado de alta", "En riesgo", "Estado critico" }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, -1));

        Modificar.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 340));

        Elegir.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("Menu Principal");
        Elegir.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel35.setText("Bienvenido");
        Elegir.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton12.setText("Agregar Paciente");
        Elegir.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, -1));

        jButton13.setText("Visualizar Paciente");
        Elegir.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 180, -1));

        jButton14.setText("Modificar Paciente");
        Elegir.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, -1));

        jButton15.setText("Eliminar Paciente");
        Elegir.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, -1));

        jButton16.setText("Cerrar Sesion");
        Elegir.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        getContentPane().add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 180, -1));

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));

        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String usuario= txtRut.getText();
        String contrasena= txtContra.getText();
        if (usuario.isEmpty() || contrasena.isEmpty()){
            JOptionPane.showMessageDialog(this, "Un campo esta vacio", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed

    private void txt_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Elegir;
    private javax.swing.JFrame Eliminar;
    private javax.swing.JFrame Ficha;
    private javax.swing.JFrame Menu;
    private javax.swing.JFrame Modificar;
    private javax.swing.JFrame Nuevo;
    private javax.swing.JFrame Visualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel rut;
    private javax.swing.JLabel rut_n;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txtrut_n;
    // End of variables declaration//GEN-END:variables
}
