/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import com.mycompany.registrohospital.Conexion;
import com.mycompany.registrohospital.Pacientes;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Set;

/**
 *
 * @author Legion
 */
public class Pantalla2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla2.class.getName());

    /**
     * Creates new form Pantalla2
     */
    public Pantalla2() {
        initComponents();
    }
    public void llenarcombo(){
        for (int i = 0; i<150; i++){
            cboxEdadP.addItem(String.valueOf(i+1));
        }
            
    }
public void agregar(){
        String nombre= txtNombreP.getText();
        String rut= txtRutP.getText();
        String apellido=txtApellidoP.getText();
        String motivo=txtMotivo_Consulta.getText();
        int edad= Integer.parseInt(cboxEdadP.getSelectedItem().toString());
        String fecha = txtFecha_Ingreso.getText();
        String pasillo="";
        if (rbA.isSelected()){
            pasillo="A";
        }
        else if (rbB.isSelected()){
            pasillo="A";
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Complete el campo nombre","Error", JOptionPane.WARNING_MESSAGE);
        }
        String estado=cboxEstado.getSelectedItem().toString();
        String pass=txtPass.getText();
        Pacientes pa = new Pacientes(rut, nombre, apellido, edad, motivo, fecha, pasillo, estado, pass);
        
        Conexion co = new Conexion();
        co.insertar(pa);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginEncargados = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        btnLoginE = new javax.swing.JButton();
        LoginPacientes = new javax.swing.JFrame();
        txtRutPaciente = new javax.swing.JTextField();
        txtPassPaciente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnLoginP = new javax.swing.JButton();
        RegistroPacientes = new javax.swing.JFrame();
        txtNombreP = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtRutP = new javax.swing.JTextField();
        cboxEdadP = new javax.swing.JComboBox<>();
        txtMotivo_Consulta = new javax.swing.JTextField();
        txtFecha_Ingreso = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        cboxEstado = new javax.swing.JComboBox<>();
        txtPassP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        pasillos = new javax.swing.ButtonGroup();
        cboxUsuario = new javax.swing.JComboBox<>();
        btnentrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        LoginEncargados.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Rut");
        LoginEncargados.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 37, -1));

        jLabel3.setText("Contraseña");
        LoginEncargados.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 125, -1, -1));

        jLabel4.setText("Login Encargados");
        LoginEncargados.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 28, 104, -1));
        LoginEncargados.getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 122, 140, -1));
        LoginEncargados.getContentPane().add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 83, 140, -1));

        btnLoginE.setText("Iniciar Sesión");
        btnLoginE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginEActionPerformed(evt);
            }
        });
        LoginEncargados.getContentPane().add(btnLoginE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        LoginPacientes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRutPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutPacienteActionPerformed(evt);
            }
        });
        LoginPacientes.getContentPane().add(txtRutPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 72, 150, -1));
        LoginPacientes.getContentPane().add(txtPassPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 124, 150, -1));

        jLabel13.setText("Rut");
        LoginPacientes.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 75, 43, -1));

        jLabel14.setText("Contraseña");
        LoginPacientes.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel15.setText("Login Pacientes");
        LoginPacientes.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        btnLoginP.setText("Iniciar Sesión");
        LoginPacientes.getContentPane().add(btnLoginP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        RegistroPacientes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        RegistroPacientes.getContentPane().add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 71, -1));
        RegistroPacientes.getContentPane().add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 71, -1));
        RegistroPacientes.getContentPane().add(txtRutP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 71, -1));

        cboxEdadP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cboxEdadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEdadPActionPerformed(evt);
            }
        });
        RegistroPacientes.getContentPane().add(cboxEdadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        RegistroPacientes.getContentPane().add(txtMotivo_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 71, -1));
        RegistroPacientes.getContentPane().add(txtFecha_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 71, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pasilllo"));

        rbA.setText("Pasillo A");

        rbB.setText("Pasillo B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA)
                    .addComponent(rbB))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        RegistroPacientes.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 260, 60));

        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dado de alta", "En riesgo", "Estado crítico" }));
        RegistroPacientes.getContentPane().add(cboxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));
        RegistroPacientes.getContentPane().add(txtPassP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 71, -1));

        jLabel5.setText("Rut");
        RegistroPacientes.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 37, -1));

        jLabel6.setText("Nombre");
        RegistroPacientes.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel7.setText("Apellido");
        RegistroPacientes.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel8.setText("Edad");
        RegistroPacientes.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel9.setText("Motivo");
        RegistroPacientes.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel10.setText("Fecha de Ingreso");
        RegistroPacientes.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 50));

        jLabel11.setText("Estado");
        RegistroPacientes.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel12.setText("Contraseña");
        RegistroPacientes.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        RegistroPacientes.getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel16.setText("Ingreso De Pacientes");
        RegistroPacientes.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encargado", "Paciente" }));
        cboxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cboxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 148, -1));

        btnentrar.setText("Entrar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa tu tipo de usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        // TODO add your handling code here:
        String tipo = cboxUsuario.getSelectedItem().toString();

        if (tipo.equals("Encargado")) {
            LoginEncargados.setVisible(true);
            LoginEncargados.resize(450,300);
        }
        else if (tipo.equals("Paciente")) {
            LoginPacientes.setVisible(true);
            LoginPacientes.resize(450,300);
        }
    }//GEN-LAST:event_btnentrarActionPerformed

    private void cboxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxUsuarioActionPerformed

    private void cboxEdadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEdadPActionPerformed
        // TODO add your handling code here:
        llenarcombo();
    }//GEN-LAST:event_cboxEdadPActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLoginEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginEActionPerformed

    private void txtRutPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame LoginEncargados;
    private javax.swing.JFrame LoginPacientes;
    private javax.swing.JFrame RegistroPacientes;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLoginE;
    private javax.swing.JButton btnLoginP;
    private javax.swing.JButton btnentrar;
    private javax.swing.JComboBox<String> cboxEdadP;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JComboBox<String> cboxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup pasillos;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtFecha_Ingreso;
    private javax.swing.JTextField txtMotivo_Consulta;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassP;
    private javax.swing.JTextField txtPassPaciente;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtRutP;
    private javax.swing.JTextField txtRutPaciente;
    // End of variables declaration//GEN-END:variables
}
